name: Merge to Main

on:
  push:
    branches: [ main ]
jobs:
  build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [ 18, 20 ]

      name: Node ${{ matrix.node }} Release
      steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
            cache: 'pnpm'
        - run: pnpm install
        - run: pnpm lint
        - run: pnpm test
