name: Pull Request

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]

    name: Node ${{ matrix.node }} PR
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
        name: install dependencies
      - run: pnpm lint
        name: linting
      - run: pnpm test:coverage
        name: testing
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: pnpm audit signatures
      - run: pnpm build
        name: build package
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v2